language: python
notifications:
  email: true
python:
  - "2.6"
  - "2.7"
install:
  - "sudo apt-get install freetds-dev vpnc python-numpy python-matplotlib python-scipy python-pymssql -qq -y"
  - "easy_install -U setuptools"
  - "pip install --upgrade pip"
  - "pip install pymssql"
script:
  - python vpn.py
after_success:
  - coveralls
