cenmet:
    AIRCEN01: AIR335
    AIRCEN02: AIR327
    AIRCEN03: AIR326
    AIRCEN04: AIR334
    AIRCEN08: AIR243
    RELCEN01: REL312
    RELCEN04: REL311
primet:
    AIRPRI01: AIR235
    AIRPRI02: AIR227
    AIRPRI03: AIR226
    AIRPRI04: AIR234
    AIRPRI06: AIR241
    AIRPRI07: AIR242
    AIRPRI08: AIR243 
    AIRPRI09: AIR244
    RELPRI01: REL212
    RELPRI04: REL211
    DEWPRI04: DEW211
h15met:
    AIRH1501: AIR335
    AIRH1502: AIR334
    RELH1502: REL314
    RELH1501: REL315
vanmet:
    AIRVAN01: AIR335
    AIRVAN02: AIR327
    AIRVAN03: AIR326
    AIRVAN04: AIR334
    AIRVAN08: AIR138
    RELVAN01: REL312
    RELVAN04: REL311
    DEWVAN01: DEW312
varmet:
    AIRVAR10: AIR228
uplmet:
    AIRUPL01: AIR335
    AIRUPL02: AIR327
    AIRUPL03: AIR326
    AIRUPL04: AIR334
    AIRUPL08: AIR138
    RELUPL04: REL311
    RELUPL01: REL312
cs2met:
    AIRCS202: AIR334
    RELCS202: REL311
    DEWCS202: DEW311