cenmet:
    AIRCEN01: AIR335
    AIRCEN02: AIR327
    AIRCEN03: AIR326
    AIRCEN04: AIR334
    AIRCEN08: AIR243
primet:
    AIRPRI01: AIR235
    AIRPRI02: AIR227
    AIRPRI03: AIR226
    AIRPRI04: AIR234
    AIRPRI06: AIR241
    AIRPRI07: AIR242
    AIRPRI08: AIR243 
    AIRPRI09: AIR244
    vanmet:
    uplmet:
