cenmet:
    ATMCEN01: ATM001
    AIRCEN01: AIR335
    AIRCEN02: AIR327
    AIRCEN03: AIR326
    AIRCEN04: AIR334
    AIRCEN08: AIR243
    RELCEN01: REL312
    RELCEN04: REL311
    LYSCEN01: LYS102
    DEWCEN01: DEW312
    DEWCEN04: DEW311
    VPDCEN04: VPD307
    VPDCEN01: VPD308
    PPTCEN01: PPT115
    PPTCEN02: PPT116
    SNOCEN01: SNO999
    SNOCEN02: SNO999
    SNOCEN03: SNO999
    SOICEN02: SOI012
    SOICEN01: SOI011
    SOICEN04: SOI014
    SOICEN04: SOI013
    SWCCEN01: SWC101
    SWCCEN02: SWC102
    SWCCEN03: SWC103
    SWCCEN04: SWC104
    RADCEN01: RAD112
    WNDCEN01: WND108
    WNDCEN02: WND111
primet:
    ATMPRI01: ATM001
    AIRPRI01: AIR235
    AIRPRI02: AIR227
    AIRPRI03: AIR226
    AIRPRI04: AIR234
    AIRPRI06: AIR241
    AIRPRI07: AIR242
    AIRPRI08: AIR243 
    AIRPRI09: AIR244
    RELPRI01: REL212
    RELPRI04: REL211
    DEWPRI01: DEW212
    DEWPRI04: DEW211
    VPDPRI04: VPD207
    VPDPRI01: VPD208
    PPTPRI01: PPT118
    SNOPRI01: SNO999
    SOIPRI04: SOI014
    SOIPRI02: SOI012
    SOIPRI01: SOI011
    SOIPRI03: SOI013
    SWCPRI04: SWC104
    SWCPRI03: SWC103
    SWCPRI02: SWC102
    SWCPRI01: SWC101
    RADPRI01: RAD112
    RADPRI02: RAD114
    WNDPRI01: WND108
    WNDPRI02: WND111
h15met:
    AIRH1501: AIR335
    AIRH1502: AIR334
    RELH1502: REL314
    RELH1501: REL315
    DEWH1501: DEW315
    DEWH1502: DEW211
    LYSH1501: SNO999
    VPDH1501: VPD310
    VPDH1502: VPD309
    PPTH1501: PPT115
    PPTH1502: PPT115
    WNDH1501: WND107
vanmet:
    AIRVAN01: AIR335
    AIRVAN02: AIR327
    AIRVAN03: AIR326
    AIRVAN04: AIR334
    AIRVAN08: AIR138
    RELVAN01: REL312
    RELVAN04: REL311
    DEWVAN01: DEW312
    DEWVAN04: DEW311
    VPDVAN01: VPD308
    VPDVAN04: VPD307
    PPTVAN01: PPT115
    PPTVAN02: PPT115
    SOIVAN09: SOI014
    SOIVAN07: SOI012
    SOIVAN06: SOI011
    SOIVAN04: SOI014
    SOIVAN03: SOI013
    SOIVAN02: SOI012
    SOIVAN01: SOI011
    SOIVAN08: SOI013
    SWCVAN01: SWC101
    SWCVAN03: SWC103
    SWCVAN04: SWC104
    SWCVAN02: SWC102
    RADVAN01: RAD110
    RADVAN02: RAD114
    WNDVAN02: WND111
    WNDVAN01: WND108
    SNOVAN03: SNO999
    SNOVAN02: SNO999
    SNOVAN01: SNO999
varmet:
    AIRVAR10: AIR228
    PPTVAR02: PPT117
    SNOVAR04: SNO999
uplmet:
    AIRUPL01: AIR335
    AIRUPL02: AIR327
    AIRUPL03: AIR326
    AIRUPL04: AIR334
    AIRUPL08: AIR138
    RELUPL04: REL311
    RELUPL01: REL312
    DEWUPL01: DEW312
    DEWUPL04: DEW311
    LYSUPL01: SNO999
    PPTUPL01: PPT115
    PPTUPL02: PPT116
    VPDUPL01: VPD308
    SOIUPL03: SOI003
    SOIUPL04: SOI004
    SOIUPL02: SOI002
    SOIUPL01: SOI001
    SWCUPL04: SWC104
    SWCUPL02: SWC102
    SWCUPL03: SWC103
    RADUPL01: RAD111
    WNDUPL01: WND108
    SNOUPL01: SNO999
    SNOUPL02: SNO999
    SNOUPL03: SNO999
cs2met:
    AIRCS202: AIR334
    RELCS202: REL311
    DEWCS202: DEW311
    VPDCS202: VPD307
    PPTCS202: PPT999
    WNDCS202: WND108