cenmet:
    AIRCEN01: AIR335
    AIRCEN02: AIR327
    AIRCEN03: AIR326
    AIRCEN04: AIR334
    AIRCEN08: AIR243
    RELCEN01: REL312
    RELCEN04: REL311
    DEWCEN01: DEW312
    DEWCEN04: DEW311
    VPDCEN04: VPD307
    VPDCEN01: VPD308
    SOICEN02: SOI012
    SOICEN01: SOI011
    SOICEN04: SOI014
    SOICEN04: SOI013
    SWCCEN01: SWC101
    SWCCEN02: SWC102
    SWCCEN03: SWC103
    SWCCEN04: SWC104
    RADCEN01: RAD112
primet:
    AIRPRI01: AIR235
    AIRPRI02: AIR227
    AIRPRI03: AIR226
    AIRPRI04: AIR234
    AIRPRI06: AIR241
    AIRPRI07: AIR242
    AIRPRI08: AIR243 
    AIRPRI09: AIR244
    RELPRI01: REL212
    RELPRI04: REL211
    DEWPRI01: DEW212
    DEWPRI04: DEW211
    VPDPRI04: VPD207
    VPDPRI01: VPD208
    SOIPRI04: SOI014
    SOIPRI02: SOI012
    SOIPRI01: SOI011
    SOIPRI03: SOI013
    SWCPRI04: SWC104
    SWCPRI03: SWC103
    SWCPRI02: SWC102
    SWCPRI01: SWC101
    RADPRI01: RAD112
h15met:
    AIRH1501: AIR335
    AIRH1502: AIR334
    RELH1502: REL314
    RELH1501: REL315
    DEWH1501: DEW315
    DEWH1502: DEW211
    VPDH1501: VPD310
    VPDH1502: VPD309
vanmet:
    AIRVAN01: AIR335
    AIRVAN02: AIR327
    AIRVAN03: AIR326
    AIRVAN04: AIR334
    AIRVAN08: AIR138
    RELVAN01: REL312
    RELVAN04: REL311
    DEWVAN01: DEW312
    DEWVAN04: DEW311
    VPDVAN01: VPD308
    VPDVAN04: VPD307
    SOIVAN09: SOI014
    SOIVAN07: SOI012
    SOIVAN06: SOI011
    SOIVAN04: SOI014
    SOIVAN03: SOI013
    SOIVAN02: SOI012
    SOIVAN01: SOI011
    SOIVAN08: SOI013
    SWCVAN01: SWC101
    SWCVAN03: SWC103
    SWCVAN04: SWC104
    SWCVAN02: SWC102
    RADVAN01: RAD110
varmet:
    AIRVAR10: AIR228
uplmet:
    AIRUPL01: AIR335
    AIRUPL02: AIR327
    AIRUPL03: AIR326
    AIRUPL04: AIR334
    AIRUPL08: AIR138
    RELUPL04: REL311
    RELUPL01: REL312
    DEWUPL01: DEW312
    DEWUPL04: DEW311
    VPDUPL01: VPD308
    SOIUPL03: SOI003
    SOIUPL04: SOI004
    SOIUPL02: SOI002
    SOIUPL01: SOI001
    SWCUPL04: SWC104
    SWCUPL02: SWC102
    SWCUPL03: SWC103
    RADUPL01: RAD111
cs2met:
    AIRCS202: AIR334
    RELCS202: REL311
    DEWCS202: DEW311
    VPDCS202: VPD307