cenmet:
    AIRCEN01: AIR248
    AIRCEN02: AIR247
    AIRCEN03: AIR246
    AIRCEN04: AIR245
    AIRCEN08: AIR243
primet:
    AIRPRI01: AIR248
    AIRPRI02: AIR247
    AIRPRI03: AIR246
    AIRPRI04: AIR241
    AIRPRI06: AIR241
    AIRPRI07: AIR242
    AIRPRI08: AIR243
    AIRPRI09: AIR244
vanmet:
    AIRVAN01: AIR248
    AIRVAN02: AIR247
    AIRVAN03: AIR246
    AIRVAN04: AIR245
    AIRVAN08: AIR243
h15met:
    AIRH1501: AIR248
varmet:
    AIRVAR10: AIR248
uplmet:
    AIRUPL01: AIR248
cs2met:
    AIRCS202: AIR334