cenmet:
    ATMCEN01: ATM001
    AIRCEN01: AIR248
    AIRCEN02: AIR247
    AIRCEN03: AIR246
    AIRCEN04: AIR245
    AIRCEN08: AIR243
    RELCEN01: REL217
    RELCEN04: REL216
    LYSCEN01: LYS102
    DEWCEN01: DEW217
    DEWCEN04: DEW216
    VPDCEN04: VPD211
    VPDCEN01: VPD212
    PARCEN01: PAR101
    PPTCEN01: PPT115
    PPTCEN02: PPT116
    SNOCEN01: SNO999
    SNOCEN02: SNO999
    SNOCEN03: SNO999
    SOICEN02: SOI012
    SOICEN01: SOI011
    SOICEN04: SOI014
    SOICEN04: SOI013
    SWCCEN01: SWC101
    SWCCEN02: SWC102
    SWCCEN03: SWC103
    SWCCEN04: SWC104
    RADCEN01: RAD112
    WNDCEN01: WND108
    WNDCEN02: WND111
primet:
    ATMPRI01: ATM001
    AIRPRI01: AIR248
    AIRPRI02: AIR247
    AIRPRI03: AIR246
    AIRPRI04: AIR241
    AIRPRI06: AIR241
    AIRPRI07: AIR242
    AIRPRI08: AIR243 
    AIRPRI09: AIR244
    RELPRI01: REL217
    RELPRI04: REL216
    DEWPRI01: DEW212
    DEWPRI04: DEW211
    VPDPRI04: VPD212
    VPDPRI01: VPD211
    PPTPRI01: PPT108
    SNOPRI01: SNO111
    SOIPRI04: SOI014
    SOIPRI02: SOI012
    SOIPRI01: SOI011
    SOIPRI03: SOI013
    SWCPRI04: SWC104
    SWCPRI03: SWC103
    SWCPRI02: SWC102
    SWCPRI01: SWC101
    RADPRI01: RAD112
    RADPRI02: RAD114
    WNDPRI01: WND108
    WNDPRI02: WND111
h15met:
    AIRH1501: AIR335
    AIRH1502: AIR334
    RELH1502: REL314
    RELH1501: REL315
    DEWH1501: DEW315
    DEWH1502: DEW314
    LYSH1501: LYS102
    VPDH1501: VPD310
    VPDH1502: VPD309
    PPTH1501: PPT106
    PPTH1502: PPT113
    WNDH1501: WND107
vanmet:
    AIRVAN01: AIR248
    AIRVAN02: AIR247
    AIRVAN03: AIR246
    AIRVAN04: AIR245
    AIRVAN08: AIR238
    RELVAN01: REL312
    RELVAN04: REL311
    DEWVAN01: DEW217
    DEWVAN04: DEW216
    VPDVAN01: VPD308
    VPDVAN04: VPD307
    PPTVAN01: PPT115
    PPTVAN02: PPT115
    SOIVAN09: SOI014
    SOIVAN07: SOI012
    SOIVAN06: SOI011
    SOIVAN04: SOI014
    SOIVAN03: SOI013
    SOIVAN02: SOI012
    SOIVAN01: SOI011
    SOIVAN08: SOI013
    SWCVAN01: SWC101
    SWCVAN03: SWC103
    SWCVAN04: SWC104
    SWCVAN02: SWC102
    RADVAN01: RAD110
    RADVAN02: RAD114
    WNDVAN02: WND111
    WNDVAN01: WND108
    SNOVAN03: SNO111
    SNOVAN02: SNO111
    SNOVAN01: SNO111
varmet:
    AIRVAR10: AIR228
    PPTVAR02: PPT117
    SNOVAR04: SNO112
uplmet:
    AIRUPL01: AIR335
    AIRUPL02: AIR327
    AIRUPL03: AIR326
    AIRUPL04: AIR334
    AIRUPL08: AIR138
    RELUPL04: REL311
    RELUPL01: REL312
    DEWUPL01: DEW312
    DEWUPL04: DEW311
    LYSUPL01: LYS102
    PPTUPL01: PPT115
    PPTUPL02: PPT116
    VPDUPL01: VPD308
    SOIUPL03: SOI003
    SOIUPL04: SOI004
    SOIUPL02: SOI002
    SOIUPL01: SOI001
    SWCUPL04: SWC104
    SWCUPL02: SWC102
    SWCUPL03: SWC103
    RADUPL01: RAD111
    WNDUPL01: WND108
    SNOUPL01: SNO113
    SNOUPL02: SNO999
    SNOUPL03: SNO999
cs2met:
    AIRCS202: AIR334
    RELCS202: REL311
    DEWCS202: DEW311
    VPDCS202: VPD307
    PPTCS202: PPT118
    WNDCS202: WND108